# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dummy.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("dummy.proto", :syntax => :proto3) do
    add_message "Dummy" do
      optional :foo, :string, 1
    end
  end
end

Dummy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Dummy").msgclass
