# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dummy.proto

require 'google/protobuf'


descriptor_data = "\n\x0b\x64ummy.proto\"\x14\n\x05\x44ummy\x12\x0b\n\x03\x66oo\x18\x01 \x01(\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

Dummy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Dummy").msgclass
